language: c
sudo: required

os:
  - linux
  - osx

compiler:
  - gcc

branches:
  only:
    - master

before_install:
  - |
    if [ $TRAVIS_OS_NAME = linux ]; then
      sudo apt-get purge cmake
      sudo apt-key update
      sudo apt-get update
      sudo apt-get -y -f install gfortran python3 cmake
    fi
  - |
    if [ $TRAVIS_OS_NAME = osx ]; then
      brew update && brew install gcc
    fi

script:
  - cd src
  - make all
  - make debug

after_success:
  - echo FEHM compilation successful